// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS8eo9D73-nV1beFBaQskoioDKPZV6u2A',
    appId: '1:58330197483:web:bb643c4241a18ac5d07dae',
    messagingSenderId: '58330197483',
    projectId: 'walkmate-2',
    authDomain: 'walkmate-2.firebaseapp.com',
    storageBucket: 'walkmate-2.firebasestorage.app',
    measurementId: 'G-2RQK1M7EE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4e7ecFE25n3QcAKfZkvgINlhha3Ln0W4',
    appId: '1:58330197483:android:35a9808cd683b806d07dae',
    messagingSenderId: '58330197483',
    projectId: 'walkmate-2',
    storageBucket: 'walkmate-2.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS8eo9D73-nV1beFBaQskoioDKPZV6u2A',
    appId: '1:58330197483:web:01b5572481d884fed07dae',
    messagingSenderId: '58330197483',
    projectId: 'walkmate-2',
    authDomain: 'walkmate-2.firebaseapp.com',
    storageBucket: 'walkmate-2.firebasestorage.app',
    measurementId: 'G-GL1GGZG9V4',
  );
}
